FROM azul/zulu-openjdk:17-latest AS build

WORKDIR /app/

COPY . /app/

RUN --mount=type=cache,target=/root/.gradle/caches/ \
 ./gradlew shadowJar

FROM azul/zulu-openjdk:17-jre-headless-latest

WORKDIR /app/

COPY hotspot-entrypoint.sh /

COPY --from=build /app/build/libs/piped-1.0-all.jar /app/piped.jar

COPY VERSION .

EXPOSE 8080

ENTRYPOINT ["/hotspot-entrypoint.sh"]
