FROM eclipse-temurin:19-jre

WORKDIR /app/

COPY ./piped.jar /app/piped.jar

COPY VERSION .

EXPOSE 8080

CMD java -server -Xmx1G -XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseNUMA -XX:+UseG1GC -Xshare:on --enable-preview -jar /app/piped.jar
