FROM ibm-semeru-runtimes:open-17-jre

WORKDIR /app/

COPY ./piped.jar /app/piped.jar

COPY VERSION .

EXPOSE 8080

CMD java -server -XX:+UnlockExperimentalVMOptions -XX:+OptimizeStringConcat -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseNUMA -XX:+UseParallelGC -XX:-UseBiasedLocking -Xshareclasses:allowClasspaths -jar /app/piped.jar
