services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - ./config.h2.properties:/app/config.properties
